# Generated by Django 4.0.6 on 2022-08-07 08:01

# this script does NOT revert
from django.db import migrations


def move_data(apps, schema_editor):

    # if the old model of the old app still exists
    try:
        ProfileOcLettings = apps.get_model("oc_lettings_site", "Profile")
        ProfileLettings = apps.get_model("profiles", "Profile")
    except LookupError:
        return

    for profile in ProfileOcLettings.objects.all():
        profile_lettings = ProfileLettings(
            user=profile.user,
            favorite_city=profile.favorite_city,
        )
        profile_lettings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ("oc_lettings_site", "0003_alter_address_id_alter_letting_id_alter_profile_id_and_more"),
    ]

    operations = [
        migrations.RunPython(move_data),
    ]
