# Generated by Django 4.0.6 on 2022-08-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO lettings_address (
                    number,
                    street,
                    city,
                    state,
                    zip_code,
                    country_iso_code
            )
            SELECT
                    number,
                    street,
                    city,
                    state,
                    zip_code,
                    country_iso_code
            FROM
                oc_lettings_site_address;
        """, reverse_sql="""
            INSERT INTO oc_lettings_site_address (
                    number,
                    street,
                    city,
                    state,
                    zip_code,
                    country_iso_code
            )
            SELECT
                    number,
                    street,
                    city,
                    state,
                    zip_code,
                    country_iso_code
            FROM
                lettings_address;
        """)
    ]
