# at src commit build docker image of the site,
# lint & test it,
# if ok then push it to dockerhub
# if ok then deploy it to heroku
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  lint_and_test:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      # get the src from GH
      - checkout
      - run:
          name: install packages
          command: |
            pip install --user --no-cache-dir -r requirements.txt
          when: always
      - run:
          name: check linting
          command: |
            flake8
      - run:
          name: run unit tests
          command: |
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build_docker_image:
    docker:
      - image: cimg/python:3.10
    resource_class: medium
    steps:
      # get the Dockerfile src from GH .circleci\images\primary\Dockerfile
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: build and deploy to dockerhub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin
            docker image build --file=.circleci/images/primary/Dockerfile --tag=$DOCKER_USERNAME/$IMAGE_REPO:$CIRCLE_SHA1 --tag=$DOCKER_USERNAME/$IMAGE_REPO:latest .
            docker image push $DOCKER_USERNAME/$IMAGE_REPO:$CIRCLE_SHA1 


  deploy_docker_to_heroku:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: deploy from docker to heroku
          command: |
            echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
            docker tag $DOCKER_USERNAME/$IMAGE_REPO:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  build_and_deploy:
    jobs:
      - lint_and_test
      - build_docker_image:
          requires:
            - lint_and_test
      - deploy_docker_to_heroku:
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - main
