# at src commit build docker image of the site,
# lint & test it,
# if ok then push it to dockerhub
# if ok then deploy it to heroku
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  lint_and_test:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      # get the src from GH
      - checkout
      - run:
          name: install packages
          command: |
            pip install --user --no-cache-dir -r requirements.txt
          when: always
      - run:
          name: check linting
          command: |
            flake8
      - run:
          name: run unit tests
          command: |
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app

  check_docker_image:
    docker:
      - image: cimg/python:3.10
    resource_class: medium
    steps:
      # get the Dockerfile src from GH .circleci\images\primary\Dockerfile
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build from the attached Dockerfile then push image to Docker Hub
      - docker_orb/check:
          docker-password: DOCKER_PASSWORD 
          docker-username: DOCKER_USERNAME
      - docker_orb/build:
          dockerfile: Dockerfile 
          path: .circleci/images/primary 
          image: ${IMAGE_NAME}
          docker-context: . 
      - docker_orb/push:
          image: ${IMAGE_NAME}
          digest-path: /tmp/digest.txt

  deploy_docker_to_heroku:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: deploy from docker to heroku
          command: |
            docker login --username=_ --password=HEROKU_API_KEY registry.heroku.com
            docker tag IMAGE_NAME registry.heroku.com/HEROKU_APP_NAME/web
            docker push registry.heroku.com/HEROKU_APP_NAME/web

workflows:
  build_and_deploy:
    jobs:
      - lint_and_test
      - check_docker_image:
          requires:
            - lint_and_test
      - deploy_docker_to_heroku:
          requires:
            - check_docker_image
          filters:
            branches:
              only:
                - main
