# at src commit build docker image of the site, 
# lint & test it, 
# if ok then push it to dockerhub
# if ok then deploy it to heroku
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build_lint_and_test:
    docker:
      - image: cimg/python:3.10
    steps:
      # get the src from GH
      - checkout
      # saved during last run ; checksum in case of dep changes
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install packages 
          command: |
            pip install --user --no-cache-dir -r requirements.txt
          when: always
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "ENV"
      - run:
          name: check linting
          command: |
            flake8 
      - run:
          name: run unti tests
          command: |
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app
  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.10
    steps:
      # get the src from GH
      - checkout
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build and push Docker image
      - run: 
          name: publish to dockerhub
          command: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/oc_lettings:$CIRCLE_SHA1 .
          docker push $DOCKER_USERNAME/oc_lettings:$CIRCLE_SHA1
  deploy_docker_to_heroku:
    executor: heroku/default
    steps:
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - docker/check:
          docker-username: $DOCKER_USERNAME
          docker-password: $DOCKER_PASSWORD
      - checkout
      - heroku/install
      - run: heroku container:login
      - run:
          name: push to heroku registry
          command: |
          # docker tag $DOCKER_USERNAME/oc-lettings:latest registry.heroku.com/$HEROKU_APP_NAME/web
          heroku/push-docker-image $DOCKER_USERNAME/oc-lettings:latest
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
  

workflows:
  build_and_test:
    jobs:
      - build_lint_and_test
  push_image_to_docker:
    jobs:
      - build_and_push_docker_image:
          requires:
            - build_lint_and_test
      #     filters:
      #       branches:
      #         only: main
  deploy_to_heroku:
    jobs:
      # - heroku/push-docker-image
      - deploy_docker_to_heroku
          requires:
            - build_and_push_docker_image
      #     filters:
      #       branches:
      #         only: main