# at src commit build docker image of the site, 
# lint & test it, 
# if ok then push it to dockerhub
# if ok then deploy it to heroku
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.2

jobs:
  build_lint_and_test:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      # get the src from GH
      - checkout
      # saved during last run ; checksum in case of dep changes
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install packages 
          command: |
            pip install --user --no-cache-dir -r requirements.txt
          when: always
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "ENV"
      - run:
          name: check linting
          command: |
            flake8 
      - run:
          name: run unit tests
          command: |
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      # get the Dockerfile src from GH .circleci\images\primary\Dockerfile
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build from the attached Dockerfile then push image to Docker Hub
      - docker/check:
          docker-password: DOCKER_PASSWORD 
          docker-username: DOCKER_USERNAME 
      - docker/build:
          dockerfile: Dockerfile 
          image: "${DOCKER_USERNAME}_lettings"
          # path: .circleci\images\primary\
      - docker/push:
          image: "${DOCKER_USERNAME}_lettings" 
          # tag: ${CIRCLE_SHA1} 

  deploy_docker_to_heroku:
    executor: heroku/default
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - docker/check:
          docker-password: DOCKER_PASSWORD 
          docker-username: DOCKER_USERNAME 
      - heroku/install
      - heroku/check-authentication:
          print-whoami: true
      - heroku/push-docker-image:
          process-types: web 
      - heroku/release-docker-image

workflows:
  build_and_deploy:
    jobs:
      - build_lint_and_test
      - build_and_push_docker_image:
        requires:
          - build_lint_and_test
      - deploy_docker_to_heroku:
        requires:
          - build_lint_and_test
          - build_and_push_docker_image
      #     filters:
      #       branches:
      #         only: main