# at src commit build docker image of the site, 
# lint & test it, 
# if ok then push it to dockerhub
# if ok then deploy it to heroku
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10


jobs:
  build_lint_and_test:
    docker:
      - image: cimg/python:3.10
    steps:
      # get the src from GH
      - checkout
      # saved during last run ; checksum in case of dep changes
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install packages 
          command: |
            pip install --user --no-cache-dir -r requirements.txt
          when: always
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "ENV"
      - run:
          name: check linting
          command: |
            flake8 
      - run:
          name: run unit tests
          command: |
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.10
    steps:
      # get the Dockerfile src from GH .circleci\images\primary\Dockerfile
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build from the attached Dockerfile then push image to Docker Hub
      - run: 
          name: publish to dockerhub
          command: |
            docker build -t ${DOCKER_USERNAME}/oc_lettings:${CIRCLE_SHA1} .
            echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
            docker push ${DOCKER_USERNAME}/oc_lettings:${CIRCLE_SHA1}

  deploy_docker_to_heroku:
    executor: heroku/default
    steps:
      - heroku/install
      - run:
          name: pull from dockerhub and push to heroku
          command: |
            docker pull ${DOCKER_USERNAME}/oc-lettings:${CIRCLE_SHA1}
            docker tag ${DOCKER_USERNAME}/oc-lettings:${CIRCLE_SHA1} /oc-lettings/web
            heroku container:login
            heroku container:push --app=/oc-lettings/web web
            heroku container:release -a /oc-lettings/web web

workflows:
  build_and_test:
    jobs:
      - build_lint_and_test
      
  push_image_to_docker:
    jobs:
      - build_and_push_docker_image:
          requires:
            - build_and_test
      #     filters:
      #       branches:
      #         only: main
  deploy_to_heroku:
    jobs:
      - deploy_docker_to_heroku:
          requires:
            - push_image_to_docker
      #     filters:
      #       branches:
      #         only: main