# Generated by Django 4.0.6 on 2022-08-10 14:39
from decouple import config
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    USERNAME = config("ADMIN_USERNAME")
    PASSWORD = config("ADMIN_PASSWORD")
    EMAIL = config("ADMIN_EMAIL")

    user = get_user_model()

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
            username=USERNAME, password=PASSWORD, email=EMAIL
        )
        admin.save()
    else:
        logger.info("Superuser already created!")


class Migration(migrations.Migration):

    dependencies = []
    operations = [migrations.RunPython(generate_superuser)]
